config/routes.rb
 Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  devise_for :users

# better way
  resources :blog_posts
  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update"
  # delete "/blog_posts/:id", to: "blog_posts#destroy"
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  # put
  # patch
  # delete

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user, foreign_key: "author", class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blog_posts, foreign_key: "author", class_name: "BlogPost"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  # authenticate users before creating new post
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, except: [:index, :new, :create] #only: [:show, :edit, :update, :destroy]
 def index
  @blog_posts = BlogPost.all
 end

 def show
  #  @blog_post = BlogPost.find(params[:id])
  # rescue ActiveRecord::RecordNotFound
  #   redirect_to root_path
 end
 def new
  # @blog_post = BlogPost.new
  @blog_post = current_user.blog_posts.build
 end
 def create
    @blog_post = current_user.blog_posts.build(blog_post_params)
    # @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
 end

 def edit
  # @blog_post = BlogPost.find(params[:id])
 end

 def update
  # @blog_post = BlogPost.find(params[:id])
  if @blog_post.update(blog_post_params)
    redirect_to @blog_post
  else
    render :edit, status: :unprocessable_entity
  end
 end

 def destroy
  # @blog_post = BlogPost.find(params[:id])
  @blog_post.destroy
  redirect_to root_path
 end


 private
 def blog_post_params
   params.require(:blog_post).permit(:title,:body)
 end

 def set_blog_post
   @blog_post = current_user.blog_posts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form|%>
<% if form.object.errors.any?%>
<div>
    <% form.object.errors.full_messages.each do |message|%>
        <div>
            <%= message%>
        </div>
    <%end%>
</div>
<%end%>
<div class="flex flex-col gap-5 item-start">

<div class="flex flex-col items-start">
<%= form.label :title%>
<%= form.text_field :title,class:" resize-none min-w-[400px] border-slate-600", placeholder:"Blog title here"%>
</div>
<div class="flex flex-col items-start">
<%= form.label :body%>
<%= form.text_area :body, class:" resize-none min-w-[400px] border-slate-600", placeholder:"Blog content here"%>
</div>
</div>

<%= form.button "Add Post", class:" bg-slate-900 text-slate-200 rounded px-2 py-1 mt-2"%>
<%end%>

app/views/blog_posts/edit.html.erb
<h1>Edit blog post</h1>
<%=render partial: "form", locals: {blog_post:@blog_post}%>
<%= button_to "Delete", @blog_post, method: :delete, data:{turbo_confirm: "Are you sure!"}%>

app/views/blog_posts/index.html.erb
<div class="w-full">
    <div class="w-full">
      <% if user_signed_in? %>
      <%# Once you remove registerable from user model we can no longer use the ones currently commented %>
        <%# <%= link_to "Profile", edit_user_registration_path %>
        <div class="flex justify-between w-full">

        <%= link_to "New blog post", new_blog_post_path, class:" no-underline bg-slate-300 text-slate-700 px-2 rounded-sm" %> 
        <%= link_to "Profile", edit_user_registration_path, class:" no-underline bg-slate-300 text-slate-700 px-2 rounded-sm" %> 
        <%= button_to "Log out", destroy_user_session_path,class:"bg-red-800 text-red-300 px-2 rounded-sm" ,method: :delete%>
        </div>
      <% else %>
    

        <%= link_to "Login", new_user_session_path, class:"text-green-900 bg-green-300 px-6 py-2 float-right rounded no-underline" %>
        <%= link_to "Sign In", new_user_registration_path, class:"text-slate-900 bg-slate-200 px-6 py-2 float-right rounded no-underline mr-2" %>

<%#      
        <%= link_to "Login", new_user_session_path, class:"text-green-900 bg-green-300 px-6 py-2 float-right rounded no-underline" %> 
     
        <%# <%=# link_to "Sign up", new_user_registration_path%> 
      <%end%>
    </div>
<h1 class="text-slate-700">Hello Rubs, Wasup</h1>
<%# <% if !user_signed_in?%> 

    <%# <%= link_to "Login", new_user_session_path, class:"text-green-900 bg-green-300 px-6 py-2 float-right rounded no-underline" %> 
    <%# <%= button_to "Sign In", new_user_registration_path, class:"text-slate-900 bg-slate-200 px-6 py-2 float-right rounded no-underline mr-2" %> 
<%# <%end %> 
</div>
<% if !@blog_posts.blank?%>
    <%@blog_posts.each do |blog_post|%>
        <div>
            <h2><%= link_to blog_post.title, blog_post%></h2>
            <p>author <%= blog_post.user.email%></p>

            <%# <h2><%= link_to blog_post.title, blog_post_path(blog_post.id)</h2> %>

            <%# <h2><%= link_to blog_post.title, "/blog_posts/#{blog_post.id}"%>
            <%# </h2>  %>
            <p><%= blog_post.body%></p> 
        </div>
    <% end %>
<% else %>
    <div class="p-3">
        <h1 class="font-semibold md:text-2xl text-xl text-red-300">No Blog Post yet! be the first.</h1>
    </div>
<% end %>
 

app/views/blog_posts/new.html.erb
<h1>Add a new post </h1>
<%=render partial: "form", locals: {blog_post:@blog_post}%>

app/views/blog_posts/show.html.erb
<h1><%= @blog_post.title %></h1>
<h2><%= @blog_post.body %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto ">
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

     <!--<div class="w-full">
      <% if user_signed_in? %>
      <%# Once you remove registerable from user model we can no longer use the ones currently commented %>
        <%# <%= link_to "Profile", edit_user_registration_path %>
        <div class="flex justify-between w-full">

        <%= link_to "New blog post", new_blog_post_path, class:" no-underline bg-slate-300 text-slate-700 px-2 rounded-sm" %> 
        <%= button_to "Log out", destroy_user_session_path,class:"bg-red-800 text-red-300 px-2 rounded-sm" ,method: :delete%>
        </div>
      <% else %>
    

        <%= link_to "Login", new_user_session_path, class:"text-green-900 bg-green-300 px-6 py-2 float-right rounded no-underline" %>
        <%= link_to "Sign In", new_user_registration_path, class:"text-slate-900 bg-slate-200 px-6 py-2 float-right rounded no-underline mr-2" %>

<%#      
        <%= link_to "Login", new_user_session_path, class:"text-green-900 bg-green-300 px-6 py-2 float-right rounded no-underline" %> 
     
        <%# <%=# link_to "Sign up", new_user_registration_path%> 
      <%end%>
     </div>-->
    <%= yield %>
  </body>
</html>